### ISSUE TITLE
SR matrix patterns often assume 16x16

### ISSUE THREAD

**Issue by scruffynerf** [scottrbailey/WLED-Utils#1]
You might want to use 16 as the width for the SR effects polling.  Most of the effects assume a 16 width I believe.
As it is, the graphics you create aren't really helpful, and don't show the true pattern

**Comment by scottrbailey** [comment]
I picked that size trying to work around the "live view" limitation of 100 pixels.  I would either have to do 16x6, or use a different method of getting color data.

**Comment by scruffynerf** [comment]
Yes, do 16x6...it would be like looking at the top of a matrix, working correctly, vs the current "nothing like what it should look like"

**Comment by scottrbailey** [comment]
I rendered on 16x8 matrix. Looks like you can do 180 pixels w/o recompiling or finding another method of getting pixel data.  Akemi is a bit squished, but otherwise, they look much better to me. If they still aren't quite right please let me know. I've only used SR on occasion.

**Comment by scruffynerf** [comment]
Nope, better but it's going back and forth incorrectly.  You could adjust the WLED settings to do serpentine (which is how you are rendering it in the gif I think) or adjust the rendering to not do that.  Or reverse that, it's doing it serpentine and you aren't doing that in the gif.  Unsure which, but that's absolutely the error, every other line is reversed.  It'll look SO much better once it's correct.

**Comment by scottrbailey** [comment]
There we go!  The 2D ones looked great as 16x8 but many of the sound reactive ones want a square. So I changed to 12x12.  I'm guessing that freqpixels and freqmap want a 16x16 matrix.  But the others seemed to turn out pretty well.  Thanks for your help.

**Comment by scruffynerf** [comment]
Yes, so much better.   Thanks for fixing that!
