### ISSUE TITLE
Instructions under "configuring" of gh-pages/sp511e_wled.md need clarification

### ISSUE THREAD

**Issue by FalconFour** [scottrbailey/WLED-Utils#11]
The section currently reads like this:

> Connect the controller to a 5-24v power supply and verify you see the WLED-AP wifi access point. If you see it, it succeeded and you can stuff it back in its enclosure and follow the [getting-started guide](https://kno.wled.ge/basics/getting-started/) to get it connected to your network and configured.
> 
> Once your basic setup is complete, go back to the "LED Settings" page.
> 
> - Configure IR by selecting "JSON remote" as the remote type. The IR pin is 5, but should already be set for you. Once you select "JSON remote" a control will appear to upload the config. Upload the 38-key config found [here](https://kno.wled.ge/interfaces/json-ir/json_infrared/).
> - Configure the two additional buttons. The power button (pin 2) is set as button 0 because its default behavior is to toggle off and on. Set button 1 to pin 13 ("M" button) and button 2 to 14 ("S" button).
> - You will need to make presets for each button action to make the "M" button cycle through effects create on preset with API Command of FX=~ and save to ID 100. Then make a second preset with FX=~- and save to 101. To cycle speed with the "S" button, you want to take bigger steps. The API commands would be SX=~16 and SX=~-16.
> - Finally, you need to map your presets to the button action. Go to Config -> "Time & Macros" and set short press on button 1 to 100 and long press to 101. If you made presets for the "S" button, set them here as well.

Problems:
- The "LED Settings" page is labeled "LED Preferences" (arguably it _SHOULD_ be called "LED Settings" in the firmware as these are not user "preferences" but rather configuration of the hardware)
- "Configure IR" is nearly impossible to find because it references the drop-down without explaining where to find it in the long, complex, extremely poorly formatted settings page. It is hidden under the "IR GPIO" line item of GPIO configuration.
- "Configure the two additional buttons" is barely passable - without laying out what all the settings should be, I can only guess that the other two buttons should be also set to "Pushbutton" instead of "Disabled" (the default).
- Finally, we get to a completely unintelligible configuration line: "making presets". There is no such place to enter presets. You can create "presets" of LED patterns, but there is no place to customize these by plain-text, such to enter this "FX=~" and other commands. This step is completely unusable as there is no place to enter these presets.
- I was able to find the button-mapping section "Config -> Time & Macros" page pretty easily, but due to the inability to create these "preset" actions, this section is useless.

I'm using `WLED_0.13.3_sp511e.bin` downloaded from this same page.

Honestly, a lot of this comes from the WLED UI's incredibly disorienting, paragraph-centered user interface (with gigantic, seven-inch-wide buttons on the settings page) that prompts a headache just looking at it. Not a great start - but since I don't need to use these buttons regularly, it ought to work fine for me without button config.

This would probably be better as a forum post, but issues is all we have 😅

**Comment by scottrbailey** [comment]
Good feedback. The target audience when writing the guide was users already familiar with WLED but new to the SP511E controller. But I'll make some updates to make it easier for those unfamiliar with WLED.

To enter those commands into a preset, you have to uncheck the "Use current state" checkbox, then it will give you a text box.

**Comment by FalconFour** [comment]
Oh yeah. I was diving into this with the SP511e as my first entry into WLED. This guide seems to be the "all signs point here" guide for getting started 😅

Fairly familiar with microcontroller fiddling, and had no problems with the flashing - but oddly, just with the setup process from there!

**Comment by scottrbailey** [comment]
Updated the guide. And be sure to check out the full WLED documentation at https://kno.wled.ge
