### ISSUE TITLE
Preset instructions for SP511E to be updated for new JSON API commands

### ISSUE THREAD

**Issue by jrb80** [scottrbailey/WLED-Utils#2]
The current instructions  to setup the mechanical buttons on the SP511E controller are depreciated,

`You will need to make presets for each button action to make the "M" button cycle through effects create on preset with API Command of FX=~ and save to ID 100. Then make a second preset with FX=~- and save to 101. To cycle speed with the "S" button, you want to take bigger steps. The API commands would be SX=~16 and SX=~-16.`

Text to be updated for new [JSON support](url) from (0.11+) onwards.

**Comment by scottrbailey** [comment]
Thanks for the feedback.  But not only is the HTTP API not deprecated, but the JSON API still does not have ~ incrementing and decrementing.  AirCookie plans on adding it, maybe it will make it in before 0.13 is released.
