### ISSUE TITLE
511E Incorrect Firmware on Guide for Sound Reactive

### ISSUE THREAD

**Issue by gxgani** [scottrbailey/WLED-Utils#5]
After digging into Serg's repository https://github.com/srg74/WLED-wemos-shield/tree/master/resources/Firmware, the stated firmware on the guide seems to be regular (Aircookie's) build for 511E.

![Screen Shot 2022-06-21 at 7 27 25 AM](https://user-images.githubusercontent.com/3357587/174798882-6d328d22-e553-4b36-a139-e11a0fe2e01a.png)

I do not believe there's actually a sound reactive build for 511E

**Comment by scottrbailey** [comment]
Serg doesn’t have a SR build. I have a build from the last time the SR team had updated the 8266 branch (0.13.0-b3). The link to it is in the screenshot you sent.
