### ISSUE TITLE
Any update on SoundReactive firmware for SP511E?

### ISSUE THREAD

**Issue by iamsujay** [scottrbailey/WLED-Utils#6]
They already released an update on SoundReactive [v0.13.3](https://github.com/atuline/WLED/releases/tag/v0.13.3) 

So just asking can we expect an update on SoundReactive WLED for SP511E in future?

**Comment by scottrbailey** [comment]
That was for ESP32 only not for ESP8266. I’m hoping with the changes being made upstream we’ll get sound support for ESP8266 again. 

Scott Bailey

**Comment by iamsujay** [comment]
Thanks for informing @scottrbailey ☺️
